module.exports = {
  apps: [
    {
      name: 'analytics-template',
      cwd: '/root/meta-project-for-mvps/frontend-viewing-site/analytics-dashboard',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PORT: 3011,
        NODE_ENV: 'production',
        HOSTNAME: '0.0.0.0',
      },
      error_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/analytics-error.log',
      out_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/analytics-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
    },
    {
      name: 'productivity-template',
      cwd: '/root/meta-project-for-mvps/frontend-viewing-site/productivity-tool',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PORT: 3012,
        NODE_ENV: 'production',
        HOSTNAME: '0.0.0.0',
      },
      error_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/productivity-error.log',
      out_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/productivity-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
    },
    {
      name: 'content-template',
      cwd: '/root/meta-project-for-mvps/frontend-viewing-site/content-creator',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PORT: 3013,
        NODE_ENV: 'production',
        HOSTNAME: '0.0.0.0',
      },
      error_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/content-error.log',
      out_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/content-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
    },
    {
      name: 'digital-template',
      cwd: '/root/meta-project-for-mvps/frontend-viewing-site/digital-download',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PORT: 3014,
        NODE_ENV: 'production',
        HOSTNAME: '0.0.0.0',
      },
      error_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/digital-error.log',
      out_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/digital-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
    },
    {
      name: 'utility-template',
      cwd: '/root/meta-project-for-mvps/frontend-viewing-site/utility-processor',
      script: 'npm',
      args: 'run start',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PORT: 3015,
        NODE_ENV: 'production',
        HOSTNAME: '0.0.0.0',
      },
      error_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/utility-error.log',
      out_file: '/root/meta-project-for-mvps/frontend-viewing-site/logs/utility-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
    },
  ],
}
